"""
Django settings for write_your_day project.

Generated by 'django-admin startproject' using Django 3.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os
import environ

env = environ.Env()
environ.Env.read_env()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-i-d-5(!2m)@15msqd8(@ala$w)+b%@=&v^4vn7r3l@bh!btrw7'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'django.contrib.humanize',
    'social_manager',
    'ckeditor',
    'chat_app',
    # 'channels'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'social_manager.request_utils.RequestMiddleware',
]

ROOT_URLCONF = 'write_your_day.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'write_your_day.wsgi.application'
# ASGI_APPLICATION = 'write_your_day.asgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'full', #refernce: https://django-ckeditor.readthedocs.io/en/latest/
    },
}
# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/


# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

# DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

STATIC_URL = '/static/'
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)

# STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


# TODO 
MEDIA_ROOT = os.path.join(BASE_DIR , 'media')
MEDIA_URL = '/media/'
AUTH_USER_MODEL = 'accounts.User'



"""For chango channel install redis. you can run InMemoryChannelLayer channel setting 
but for prod you need to run channel on redis for realtime chat on different browser.
"""
# CHANNEL_LAYERS = {
#     'default': {
#         # 'BACKEND': 'channels.layers.InMemoryChannelLayer', #fot development
#         'BACKEND': 'channels_redis.core.RedisChannelLayer', #fot production
#         'CONFIG': {
#             'hosts': [('127.0.0.1', 6379)],
#         }
#     }
# }

# #SMTP Config
# EMAIL_BACKEND = env.str( 
#     "EMAIL_BACKEND", ""
# )
# EMAIL_HOST = env.str("EMAIL_HOST", "")
# EMAIL_HOST_USER = env.str("EMAIL_HOST_USER", "")
# EMAIL_HOST_PASSWORD = env.str("EMAIL_HOST_PASSWORD", "")
# EMAIL_USE_TLS = env.bool("EMAIL_USE_TLS", False)
# EMAIL_PORT = env.int("EMAIL_PORT", 25)
# DEFAULT_FROM_EMAIL = env.str("DEFAULT_FROM_EMAIL", EMAIL_HOST_USER)

# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_USE_TLS = True
# EMAIL_PORT = 587
# EMAIL_HOST_USER = 'info.writeyourday@gmail.com'
# EMAIL_HOST_PASSWORD = 'R@GH@V@123'
BASE_URL = 'http://127.0.0.1:8000'
LOGIN_REDIRECT_URL = '/'
LOGIN_URL='/accounts/login/'

EMAIL_HOST = 'smtp.mailtrap.io'
EMAIL_HOST_USER = 'e69484ee1c847a'
EMAIL_HOST_PASSWORD = 'c0ca7063a32793'
EMAIL_PORT = '2525'