# Generated by Django 3.2.12 on 2022-03-11 05:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_manager', '0002_auto_20220311_0552'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(related_name='followers', through='social_manager.Follow', to=settings.AUTH_USER_MODEL),
        ),
    ]
