# Generated by Django 3.2 on 2022-03-31 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_usernotification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserNotification',
        ),
    ]
