# Generated by Django 3.2.12 on 2022-03-11 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postcomments',
            options={'verbose_name_plural': 'Post Comments'},
        ),
        migrations.AlterModelOptions(
            name='userposts',
            options={'verbose_name_plural': 'User Posts'},
        ),
    ]
