# Generated by Django 3.2 on 2022-03-14 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_manager', '0003_postsave'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcomments',
            old_name='created_at',
            new_name='created',
        ),
    ]
