# Generated by Django 3.2 on 2022-03-15 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_manager', '0004_rename_created_at_postcomments_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='userposts',
            name='slug',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
