# Generated by Django 3.2 on 2022-03-23 02:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social_manager', '0006_auto_20220316_0504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userposts',
            name='views',
        ),
        migrations.AddField(
            model_name='userposts',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='views', to=settings.AUTH_USER_MODEL),
        ),
    ]
