# Generated by Django 3.2 on 2022-04-01 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_manager', '0008_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.IntegerField(choices=[(1, 'Like'), (2, 'Comment'), (3, 'Follow'), (4, 'Comment Like')]),
        ),
    ]
